development:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  minerthreads: 1
  genesis_block: config/genesis/dev_genesis.json
  datadir: /tmp/embark
  chains: config/chains/development.json
  mine_when_needed: true
  gas_limit: 500000
  gas_price: 10000000000000
  console: false
  account:
    init: true
    password: config/password
staging:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 0
  deploy_timeout: 45
  console: true
  account:
    init: false
    address:
production:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 1
  console: true
  account:
    init: false
    address:
